### ISSUE TITLE
Copyright statements at the start of source code files have not working links

### ISSUE THREAD

**Issue by abotalov** [reportportal/reportportal#10]
See e.g. https://github.com/reportportal/commons-dao/blob/master/src/main/java/com/epam/ta/reportportal/database/ActivityDocumentHandler.java

The link in a copyright statement is "https://github.com/epam/ReportPortal".
This link seems to be invalid.

**Comment by avarabyeu** [comment]
@DzmitryKavalets could you please re-generate file headers in all modules

**Comment by DzmitryKavalets** [comment]
fixed

**Comment by abotalov** [comment]
By the way, headers in some repositories seem to be still not fixed:
* https://github.com/reportportal/service-registry/blob/master/src/main/java/com/epam/reportportal/registry/RegistryApp.java
* https://github.com/reportportal/service-ui/blob/master/src/main/java/com/epam/reportportal/ui/UIApp.java
* https://github.com/reportportal/service-gateway/blob/master/src/main/java/com/epam/reportportal/gateway/CompositeInfoEndpoint.java
* https://github.com/reportportal/client-java-core/blob/master/src/main/java/com/epam/reportportal/exception/InternalReportPortalClientException.java
* https://github.com/reportportal/client-java-rest-core/blob/master/src/main/java/com/epam/reportportal/restclient/endpoint/AuthClientFactory.java
* https://github.com/reportportal/commons-bugtracking/blob/master/src/main/java/com/epam/reportportal/extension/bugtracking/BugTrackingApp.java
* https://github.com/reportportal/commons-rules/blob/master/src/main/java/com/epam/ta/reportportal/commons/ExceptionMappings.java
* https://github.com/reportportal/commons-model/blob/master/src/main/java/com/epam/ta/reportportal/ws/model/dashboard/CreateDashboardRQ.java
* https://github.com/reportportal/commons/blob/master/src/main/java/com/epam/reportportal/commons/ContentTypeResolver.java
