### ISSUE TITLE
SAML integration with Keycloak is not working

### ISSUE THREAD

**Issue by ostratila** [reportportal/reportportal#1115]
Hello,

I'm trying to integrate Report Portal with Keycloak through SAML.
I need to use the "Full name" attribute mode because I want to map it with the Keycloak username.

Even if I specify the full name of the attribute in the last box, I got that it is empty, see the attachment.

Can you please advise?

![image](https://user-images.githubusercontent.com/47818847/90483089-e08f5a80-e13c-11ea-806f-9cdf05a7e11c.png)

Thanks,
Oana

**Comment by evjlobanova** [comment]
@Yumfriez Vanya, could you please check issue?

**Comment by ostratila** [comment]
Hello! Are there any updates on the above issue?

**Comment by evjlobanova** [comment]
Now it is vacation time, so we can respond with delay

**Comment by evjlobanova** [comment]
@VolhaKarenko Could you please try to reproduce this issue and create a ticket in a backlog if needed

**Comment by VolhaKarenko** [comment]
> @VolhaKarenko Could you please try to reproduce this issue and create a ticket in a backlog if needed
The issue is valid, added to backlog

**Comment by ostratila** [comment]
Hello,

Thanks for the update. Can you please provide an ETA for this?

Thanks,
Oana

**Comment by evjlobanova** [comment]
For now, I can not tell you ETA.
I will update this ticket accordingly

**Comment by ostratila** [comment]
Hello! Are there any news about this?
Thanks,
Oana

**Comment by VolhaKarenko** [comment]
@ostratila Hello! 
The issue is still in progress. The workaround for now is to configure new SAML integration from scratch with "Full name" attribute.

**Comment by mc-marcy** [comment]
i get the error message not valid Login Requester. is this linked to this issue?
can anybody give me a hint what are the settings in keycloak for the client?
thanks

**Comment by jibby0** [comment]
We're seeing an issue when integrating with Keycloak as well, on our ReportPortal 5.3.0 instance. The Keycloak logs show:

```
request validation failed: org.keycloak.common.VerificationException: SigAlg was null
```

I'm not familiar with the spring ecosystem, but that lead me to this bug: https://github.com/spring-projects/spring-security/issues/7711#issuecomment-613799630

For reference, we were using the following SAML configuration:

```
Identity provider name ID

  urn:oasis:names:tc:SAML:2.0:nameid-format:persistent

Provider name

  okta

Metadata URL

  https://<keycloak server URL>/<realm path>/protocol/saml/descriptor

Email

  X500 email

Name attributes mode

  First & last name

First name

  X500 givenName

Last name

  X500 surname

**Comment by svettsova** [comment]
the fix will be available in 5.4

**Comment by ostratila** [comment]
@svettsova do you know approximately when 5.4 will be released?

**Comment by mc-marcy** [comment]
5.4 is released but in the notes is no hint related to this topic here. is it a part of the release or not?

**Comment by navilg** [comment]
@ostratila Were you able to fix this ?

**Comment by evjlobanova** [comment]
@navilg I will check tomorrow with the team this issue, and get back to you

**Comment by VolhaKarenko** [comment]
Hi @navilg, we have fixed the problem with the error from the screenshot in version 5.4. Seems like your issue has another root cause. Please create a separate issue providing some information about your configuration and error logs

**Comment by mpwmc** [comment]
@VolhaKarenko thank you, we will update to 5.4 and test again. Is the SAML integration still showing as only okta?

**Comment by evjlobanova** [comment]
Yes, it is
