### ISSUE TITLE
Unable to finish launch in Report Portal 

### ISSUE THREAD

**Issue by vellyr8x8** [reportportal/reportportal#1936]
Hi Team,
I'm facing intermittent issues where its noticed that RP logs display below mentioned error messages and fail to finish the launch in RP. This results in my build being stuck for hours until aborted. Can someone help root cause this issue?

**Screenshots**
![image](https://user-images.githubusercontent.com/94951386/219323173-d769508c-dab5-4b32-a078-4ce0d484a372.png)

**Complete Error As Displayed**
2023-02-15 22:09:08.814 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.814 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.814 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.814 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.814 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.814 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.814 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.814 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.814 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.814 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.814 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.816 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.816 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.816 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Item io.reactivex.internal.operators.maybe.MaybeEmpty@36b6964d not found in the cache
2023-02-15 22:09:08.837 ERROR 68778 --- [           main] com.epam.reportportal.service.Launch     : Unable to finish launch in ReportPortal

java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302) ~[na:1.8.0_191]
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231) ~[na:1.8.0_191]
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGetError(BlockingMultiObserver.java:131) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.Completable.blockingGet(Completable.java:1277) ~[rxjava-2.2.21.jar:na]
	at com.epam.reportportal.service.LaunchImpl.finish(LaunchImpl.java:217) ~[client-java-5.1.9.jar:na]
	at com.epam.reportportal.service.launch.PrimaryLaunch.finish(PrimaryLaunch.java:72) [client-java-5.1.9.jar:na]
	at com.epam.reportportal.cucumber.AbstractReporter.afterLaunch(AbstractReporter.java:202) [agent-java-cucumber6-5.1.2.jar:na]
	at com.epam.reportportal.cucumber.ScenarioReporter.afterLaunch(ScenarioReporter.java:109) [agent-java-cucumber6-5.1.2.jar:na]
	at com.epam.reportportal.cucumber.AbstractReporter.lambda$getTestRunFinishedHandler$33(AbstractReporter.java:802) [agent-java-cucumber6-5.1.2.jar:na]
	at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51) ~[cucumber-core-6.6.1.jar:6.6.1]
	at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12) ~[cucumber-core-6.6.1.jar:6.6.1]
	at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:93) ~[cucumber-core-6.6.1.jar:6.6.1]
	at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:74) ~[cucumber-core-6.6.1.jar:6.6.1]
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:236) ~[cucumber-junit-6.9.1.jar:6.9.1]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.runChild(Suite.java:128) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.runChild(Suite.java:27) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:367) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.runChild(Suite.java:128) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.Suite.runChild(Suite.java:27) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:367) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) ~[junit-4.13.2.jar:4.13.2]
	at org.apache.maven.surefire.junitcore.pc.ParallelComputerBuilder$PC$1.run(ParallelComputerBuilder.java:590) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158) ~[surefire-junit47-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) ~[surefire-booter-2.22.2.jar:2.22.2]

**Versions:**
 - MacOS, Chrome browser
 - Version of RP : 5.1.2

**Comment by alena-babrova** [comment]
Hello @vellyr8x8,
Could you please update to the latest version of RP and try again?

**Comment by andrewfroze** [comment]
I have the same problem (unable to finish launch) with latest version (5.1.3), but with another stucktrace:
`
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess(MaybeFlatten.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:66)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeFlatten.subscribeActual(MaybeFlatten.java:42)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@57d98b94[Not completed, task = null] rejected from java.util.concurrent.ThreadPoolExecutor@6ca448ea[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:753)
	at io.reactivex.internal.schedulers.ExecutorScheduler.scheduleDirect(ExecutorScheduler.java:59)
	... 18 more
`

**Comment by andrewfroze** [comment]
@alena-babrova, are you talking about "**commons-model**" library? We haven't used it before, I talked about **agent-java-testng**... I'll add first one and recheck

**Comment by alena-babrova** [comment]
Dear @andrewfroze,
I am talking about ReportPortal project version, which is hosted on your server. At the moment versions 5.1.2 or 5.1.3 are out-dated and it is recommended to use one of the latest versions.

**Comment by andrewfroze** [comment]
@alena-babrova, ah, now I understend.. then we use latest (5.7.3) (we are using EPAM's RP)

**Comment by Kchebulaev** [comment]
I got the same
**Versions:**
RP Build: 5.7.4
<groupId>com.epam.reportportal</groupId>
<artifactId>agent-allure-testng</artifactId>
<version>5.1.0</version>

`31:42.394 [com.epam.reportportal.service.Launch:ERROR]: Item io.reactivex.internal.operators.maybe.MaybeCache@cc04836 not found in the cache
31:42.396 [com.epam.reportportal.service.Launch:ERROR]: Item io.reactivex.internal.operators.maybe.MaybeCache@4f4dd56c not found in the cache
31:42.611 [org.asynchttpclient.netty.handler.WebSocketHandler:WARN]: onError
java.net.SocketException: Connection reset
	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258) ~[netty-buffer-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.78.Final.jar:4.1.78.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
мар. 31, 2023 12:31:42 PM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by alena-babrova** [comment]
Hello @APiankouski,
Could you please take a look at this issue? Maybe you can suggest here?

**Comment by jricardodeleon** [comment]
Was this issue solved? I'm experimenting the same.

**Comment by alena-babrova** [comment]
Hello @jricardodeleon,
What version of ReportPortal do you use? What agent?
It would be very helpful to see the server logs (API-service) when the issue happening.
Could you please provide it?

**Comment by yodaqua** [comment]
Hi there,

I'm experiencing the same issue.

Cucumber agent: 5.2.0
Helm chart: reportportal-5.7.2

I'm going to get my team deploy the latest version based on the latest helm chart. We'll retest and post our findings here. In the meantime, I have attached the serviceapi logs I got from the POD.

Server logs (API):
[logs-from-api-in-reportportal-api-58d97b6f94-rgpzv.log](https://github.com/reportportal/reportportal/files/12655683/logs-from-api-in-reportportal-api-58d97b6f94-rgpzv.log)

**Comment by alena-babrova** [comment]
Hello @yodaqua,
As for your situation, you haven't specify launch name. Pay attention to error in logs:
_[Field error in object 'startLaunchRQ' on field 'name': rejected value [null]_
Is it true that you received failure when starting launch?

**Comment by jricardodeleon** [comment]
Hello Alena,

My problem was fixed, someone from my team added a dependency and It got
solved. Thank you.

**Comment by alena-babrova** [comment]
Dear @vellyr8x8, @andrewfroze, @Kchebulaev, @yodaqua,
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
