### ISSUE TITLE
Cucumber-JVM: RP throws exception, when there is no features match the filter

### ISSUE THREAD

**Issue by SKharlanov** [reportportal/reportportal#220]
Run set of features by any filter using the following parameters _-Dcucumber.options=--tags @anyTag_.
If there is no feature marked by tag _@anyTag_, Cucumber says:
_**None of the features at [classpath:com/epam/] matched the filters: [@anyTag]**_

Report Portal creates launch and item in launch:
DEBUG - ReportPortal launch with ID 'launchID' has been created.
DEBUG - ReportPortal item with ID 'itemID' has been created.

Then Report Portal throws exception:
`ERROR - ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: 
Error Message: Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id 'itemID'
Error Type: AMBIGUOUS_TEST_ITEM_STATUS

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
	at rp.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at rp.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at rp.org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
	at rp.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at rp.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:745)
io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 400
Status message: 
Error Message: Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id 'itemID'
Error Type: AMBIGUOUS_TEST_ITEM_STATUS

	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
	at io.reactivex.internal.operators.completable.CompletableCache.onError(CompletableCache.java:81)
	at io.reactivex.internal.operators.maybe.MaybeIgnoreElementCompletable$IgnoreMaybeObserver.onError(MaybeIgnoreElementCompletable.java:73)
	at io.reactivex.internal.operators.maybe.MaybeDoAfterSuccess$DoAfterObserver.onError(MaybeDoAfterSuccess.java:81)
	at io.reactivex.internal.operators.maybe.MaybeDelayWithCompletable$DelayWithMainObserver.onError(MaybeDelayWithCompletable.java:107)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onError(MaybeFlatten.java:125)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onError(MaybeFlatten.java:103)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:94)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:569)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
	at rp.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at rp.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at rp.org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
	at rp.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at rp.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: 
Error Message: Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id 'itemID'
Error Type: AMBIGUOUS_TEST_ITEM_STATUS

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
	... 17 more
Exception in thread "I/O dispatcher 1" io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error
Status code: 400
Status message: 
Error Message: Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id 'itemID'
Error Type: AMBIGUOUS_TEST_ITEM_STATUS

	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
	at io.reactivex.internal.operators.completable.CompletableCache.onError(CompletableCache.java:81)
	at io.reactivex.internal.operators.maybe.MaybeIgnoreElementCompletable$IgnoreMaybeObserver.onError(MaybeIgnoreElementCompletable.java:73)
	at io.reactivex.internal.operators.maybe.MaybeDoAfterSuccess$DoAfterObserver.onError(MaybeDoAfterSuccess.java:81)
	at io.reactivex.internal.operators.maybe.MaybeDelayWithCompletable$DelayWithMainObserver.onError(MaybeDelayWithCompletable.java:107)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onError(MaybeFlatten.java:125)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onError(MaybeFlatten.java:103)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:94)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:569)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
	at rp.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at rp.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at rp.org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
	at rp.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at rp.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: 
Error Message: Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id 'itemID'
Error Type: AMBIGUOUS_TEST_ITEM_STATUS

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
	... 17 more
DEBUG - http-outgoing-0 [CLOSED] [chunk-coded; completed: true]
DEBUG - http-outgoing-0 [CLOSED]: Disconnected
ERROR - Unable to finish launch in ReportPortal
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: 
Error Message: Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id 'itemID'
Error Type: AMBIGUOUS_TEST_ITEM_STATUS

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
	at rp.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at rp.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at rp.org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
	at rp.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at rp.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by avarabyeu** [comment]
@SKharlanov Sergey is it possible to reproduce it in some branch of https://github.com/reportportal/example-java-cucumber?

**Comment by DzmitryHumianiuk** [comment]
@SKharlanov still actual?

**Comment by thasherwin** [comment]
I saw this issue today when executing tests.. I am checking if i can reproduce this.. Also it seems like once i get this issue my test is logged as failure. Is there a way to ignore these kind of errors and make sure that the build wont fail due to a reportportal issue?

**Comment by DzmitryHumianiuk** [comment]
@SKharlanov @thasherwin is it possible to create a simple codebase, which can reproduce this issue?
we can't reproduce it still, and this is stopper for us.

**Comment by YuliyaHancharenka** [comment]
Hi, my team reproduced this issue too.

Steps to reproduce:
1. Run a launch with **several** features, but there are only several (or one) tests in **one** feature are executing and reporting 

Expected result:
Tests are reported in RP, launch isn't hanged

Actual Result:
Tests are reported in RP, launch is hanged because other UNexecuted features throws exception, with the following error:

`2018-10-30 09:51:53,404 ERROR Launch - [48] ReportPortal execution error
build	30-Oct-2018 08:51:53	com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
build	30-Oct-2018 08:51:53	Status code: 400
build	30-Oct-2018 08:51:53	Status message: Bad Request
build	30-Oct-2018 08:51:53	Error Message: Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id '5bd81ba93cdea20001c8dd03'
build	30-Oct-2018 08:51:53	Error Type: AMBIGUOUS_TEST_ITEM_STATUS
build	30-Oct-2018 08:51:53	
build	30-Oct-2018 08:51:53		at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:57)
build	30-Oct-2018 08:51:53		at com.epam.reportportal.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
build	30-Oct-2018 08:51:53		at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:486)
build	30-Oct-2018 08:51:53		at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.call(HttpClientRestEndpoint.java:455)
build	30-Oct-2018 08:51:53		at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
build	30-Oct-2018 08:51:53		at io.reactivex.Maybe.subscribe(Maybe.java:3727)
build	30-Oct-2018 08:51:53		at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
build	30-Oct-2018 08:51:53		at io.reactivex.Maybe.subscribe(Maybe.java:3727)
build	30-Oct-2018 08:51:53		at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
build	30-Oct-2018 08:51:53		at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
build	30-Oct-2018 08:51:53		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
build	30-Oct-2018 08:51:53		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
build	30-Oct-2018 08:51:53		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
build	30-Oct-2018 08:51:53		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299)
build	30-Oct-2018 08:51:53		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
build	30-Oct-2018 08:51:53		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
build	30-Oct-2018 08:51:53		at java.base/java.lang.Thread.run(Thread.java:844)
error	30-Oct-2018 08:51:53	io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error`

See com.epam.reportportal.service.LaunchImpl.finishTestItem(Maybe<String>, FinishTestItemRQ): method logic is not according the case, when feature is run without tests to execute.

**Comment by DzmitryHumianiuk** [comment]
@YuliyaHancharenka good catch!
@akoltochihin could you plz also take a look?

**Comment by RG108** [comment]
@DzmitryHumianiuk 
@akoltochihin , @YuliyaHancharenka 

Could you please let me know if the above issue is fixed in latest RP because i am getting the below issue :
12:45:54.331 [RxCachedThreadScheduler-2] ERROR com.epam.reportportal.service.Launch - [18] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id '5cf76c2b42eba4000110de89'
Error Type: AMBIGUOUS_TEST_ITEM_STATUS

Kindly suggest !

**Comment by DzmitryHumianiuk** [comment]
@akoltochihin @filland any thoughts?

**Comment by RG108** [comment]
the issue is fixed so kindly close the issue.

**Comment by filland** [comment]
@DzmitryHumianiuk created a ticket for this issue

**Comment by yasin24885shaikh** [comment]
> the issue is fixed so kindly close the issue.

I am still getting this issue with cucumber 4. Please refer 
https://github.com/reportportal/agent-java-cucumber4/issues/28
