### ISSUE TITLE
Incorrect results count because of Deadlock in statistics table

### ISSUE THREAD

**Issue by heilwood** [reportportal/reportportal#2502]
**Describe the bug**
We faced with issue that in reportportal shown incorrect failed tests count and sometimes launch not finished automatically, we are using VSTEST with retry failed tests option. We found in postgres docker container next exception.

**Expected behavior**
```
        Process 451615 waits for ShareLock on transaction 90973201; blocked by process 451444.
        Process 451444: SELECT handle_retry($1, $2)
        Process 451615: SELECT handle_retry($1, $2)
2025-02-27 07:40:55.266 GMT [451444] HINT:  See server log for query details.
2025-02-27 07:40:55.266 GMT [451444] CONTEXT:  while updating tuple (73558,36) in relation "statistics"
        SQL statement "UPDATE statistics
                    SET s_counter = s_counter - cur_statistics_fields.s_counter
                    WHERE statistics.statistics_field_id = cur_statistics_fields.statistics_field_id
                      AND (launch_id = cur_launch_id OR (item_id = ANY(processed_test_item.arr_path) AND item_id != test_item_id))"
        PL/pgSQL function delete_item_statistics(bigint) line 29 at SQL statement
        SQL statement "SELECT delete_item_statistics(retry_id)"
        PL/pgSQL function handle_retry(bigint,bigint) line 30 at PERFORM
2025-02-27 07:40:55.266 GMT [451444] STATEMENT:  SELECT handle_retry($1, $2)
2025-02-27 07:41:05.266 GMT [451671] ERROR:  deadlock detected
2025-02-27 07:41:05.266 GMT [451671] DETAIL:  Process 451671 waits for ShareLock on transaction 90973202; blocked by process 451615.
        Process 451615 waits for ShareLock on transaction 90973200; blocked by process 451671.
        Process 451671: SELECT handle_retry($1, $2)
        Process 451615: SELECT handle_retry($1, $2)
2025-02-27 07:41:05.266 GMT [451671] HINT:  See server log for query details.
2025-02-27 07:41:05.266 GMT [451671] CONTEXT:  while updating tuple (73558,50) in relation "statistics"
        SQL statement "UPDATE statistics
            SET s_counter = s_counter - 1
            WHERE statistics_field_id = defect_field_old_total_id AND launch_id = cur_launch_id"
        PL/pgSQL function delete_defect_statistics() line 59 at SQL statement
        SQL statement "DELETE FROM issue WHERE issue_id = test_item_id"
        PL/pgSQL function delete_item_statistics(bigint) line 20 at SQL statement
        SQL statement "SELECT delete_item_statistics(retry_id)"
        PL/pgSQL function handle_retry(bigint,bigint) line 30 at PERFORM
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/dcc68ad7-af8a-4e90-8987-a61151db78b6)

**Versions:**
**Test adapter:** MSTEST
**ReportPortal: 25.03** - latest
**Nugets:**
```
  <PackageReference Include="ReportPortal.Client" Version="3.10.0" /> 
  <PackageReference Include="ReportPortal.Extensions.CI" Version="0.5.0" />
  <PackageReference Include="ReportPortal.Reqnroll" Version="1.2.0" />
  <PackageReference Include="ReportPortal.Serilog" Version="2.0.0" /> 
  <PackageReference Include="ReportPortal.Shared" Version="3.10.0" />
```

We are not sure is this is related or maybe we not tested properly, but this issue was raised after we selected defect types for our failed tests and auto-analysis started to work (it's also analyzing between retries and maybe locking something, but this is just idea)

**Comment by heilwood** [comment]
we tested more and deadlock happens only when auto-analysis is enabled, looks like ReportPorta.Extensions.CI which trying to update launch statistics between tests retries conflicting with auto-analysis which are started also between retries.

**Comment by irynakozak2** [comment]
@heilwood Hi! Thank you for your detailed information regarding the issue. It's a known issue on the latest version, besides, we plan to address it in the upcoming versions of RP. I will return to you shortly as soon as the version with the fix is released.

**Comment by Pink-Bumblebee** [comment]
Hello @heilwood . We released new version [25.1](https://reportportal.io/docs/releases/Version25.1) of ReportPortal. There are a lot of improvements and fixes.

**Comment by kusedu** [comment]
@Pink-Bumblebee deadlock is still present, bug is not resolved.

```Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 3351 waits for ShareLock on transaction 201376140; blocked by process 3365.
Process 3365 waits for ShareLock on transaction 201376145; blocked by process 3351.
  Hint: See server log for query details.
  Where: while updating tuple (66651,175) in relation "statistics"
SQL statement "UPDATE statistics
    SET s_counter = s_counter - 1
    WHERE statistics_field_id = defect_field_old_total_id AND launch_id = cur_launch_id"
PL/pgSQL function delete_defect_statistics() line 59 at SQL statement
SQL statement "DELETE FROM issue WHERE issue_id = test_item_id"
PL/pgSQL function delete_item_statistics(bigint) line 20 at SQL statement
SQL statement "SELECT delete_item_statistics(retry_id)"
PL/pgSQL function handle_retry(bigint,bigint) line 30 at PERFORM```

**Comment by heilwood** [comment]
> Hello [@heilwood](https://github.com/heilwood) . We released new version [25.1](https://reportportal.io/docs/releases/Version25.1) of ReportPortal. There are a lot of improvements and fixes.

@Pink-Bumblebee deadlock is still present, bug is not resolved.
```
  Detail: Process 3351 waits for ShareLock on transaction 201376140; blocked by process 3365.
Process 3365 waits for ShareLock on transaction 201376145; blocked by process 3351.
  Hint: See server log for query details.
  Where: while updating tuple (66651,175) in relation "statistics"
SQL statement "UPDATE statistics
    SET s_counter = s_counter - 1
    WHERE statistics_field_id = defect_field_old_total_id AND launch_id = cur_launch_id"
PL/pgSQL function delete_defect_statistics() line 59 at SQL statement
SQL statement "DELETE FROM issue WHERE issue_id = test_item_id"
PL/pgSQL function delete_item_statistics(bigint) line 20 at SQL statement
SQL statement "SELECT delete_item_statistics(retry_id)"
PL/pgSQL function handle_retry(bigint,bigint) line 30 at PERFORM

**Comment by irynakozak2** [comment]
Hello @heilwood ! Could you please share some details regarding your reporting? How many launches in parallel, total tests, max retries per test, reporting type from reportportal.properties (sync or async), and/or some specific custom cases/configurations? And it would be super beneficial to look through your compute resources for the ReportPortal installation (CPU/Memory).

Looking forward to your reply.

**Comment by heilwood** [comment]
> Hello [@heilwood](https://github.com/heilwood) ! Could you please share some details regarding your reporting? How many launches in parallel, total tests, max retries per test, reporting type from reportportal.properties (sync or async), and/or some specific custom cases/configurations? And it would be super beneficial to look through your compute resources for the ReportPortal installation (CPU/Memory).
> 
> Looking forward to your reply.

* 1 launch per project in parallel
* Total tests 480
* Max retries count 3 (using VSTEST)
* We are not using reportportal.properties we are using reportportal.config.json with default configuration, changing only API key and launch name.
* 8 cores CPU, 16GB memory.

I think scenario looks like that:

1. We are running tests using vstest
2. When execution is finished vstest looking for failed tests which should be re-executed, also when execution is finished for first run automatically started auto-analysis and i think ReportPortal.Extention.CI and auto-analysis both trying to update info in statics table and we are getting deadlock (i'm not sure for 100% but it looks like that).

**Comment by irynakozak2** [comment]
I agree. We specifically tested this case under the asynchronous reporting (/v2 endpoint), where the issue was previously reproduced, and the deadlock isn't observed on 25.1 under the same workload.

**Comment by heilwood** [comment]
> I agree. We specifically tested this case under the asynchronous reporting (/v2 endpoint), where the issue was previously reproduced, and the deadlock isn't observed on 25.1 under the same workload.

We had 30-40 failed tests when we started to get deadlock, when we have small amount of failed tests its also working

**Comment by ramadevi04g** [comment]
Hello team, we are facing the same issue. 
RP version 24.1.
Postgres SQL: 15.1
RabbitMQ on AWS
Based on our analysis, the issue is...
The deadlock was triggered by a defect statistics cleanup operation that happens when deleting issues/defects in Report Portal.
### **The Complete Execution Flow**
**Process 15018 was executing:**
Primary Operation: DELETE FROM public.issue WHERE issue_id=$1
Triggered Function: delete_defect_statistics() (PostgreSQL function)
Function Operation: UPDATE statistics SET s_counter = s_counter - 1 WHERE statistics_field_id = defect_field_old_id AND launch_id = cur_launch_id
Specific Record: Updating tuple (405290,37) in the statistics table.

**Process 15129 was executing:**
UPDATE public.test_item_results SET duration=$1, end_time=$2, status=$3 WHERE result_id=$4

Lock Acquisition Order Conflict:
Process 15018:
Acquired lock on issue table (for DELETE)

Process 15129:
Acquired lock on test_item_results table (for UPDATE)
Possibly needed a lock on the statistics table (for related counters)
Created circular dependency with Process 15018

**The Complete Failure Cascade**
**Step-by-Step Breakdown**

1. Database deadlock occurs
2. Database connection gets stuck waiting for locks (41.5 seconds)
3. Connection pool exhaustion - all connections blocked/timeout
4. The application can't access the database for any operations
5. Health check endpoints fail (database connection fails)
6. Pods get restarted due to readiness probe failures
7. New pods start → New database connections → New RabbitMQ queues.

In the short term, we clean orphaned RabbitMQ queues on a regular basis.

Any help with resolving the issue would be greatly appreciated. Unfortunately, we are not yet ready to upgrade the service to a newer version, as mentioned in the previous comment in this thread. Also, we are heavily using the system. We create almost 4000 launches per day.

**Comment by heilwood** [comment]
ReportPortal team plan to fix this issue?

**Comment by heilwood** [comment]
using asyncReporting with postgres recommended settings we don't see anymore deadlock in logs

**Comment by heilwood** [comment]
We tested more and same deadlock still present but not so often as before

**Comment by ramadevi04g** [comment]
We upgraded to 25.1.12 and tested. No luck; in fact, the number of deadlocks increased, causing the Service API to lose the DB connection and leading to frequent restarts due to unhealthy status. As a result, we eventually rolled back to version 24.2. 
`{
    "time": "2025-11-13T17:50:00.015541337Z",
    "stream": "stdout",
    "_p": "F",
    "log": "2025-11-13T17:50:00.015Z ERROR 1 --- [api] [a.Spring.bean-1] o.s.t.s.TransactionSynchronizationUtils  : TransactionSynchronization.afterCompletion threw exception",
    "kubernetes": {
        "pod_name": "reportportal-api-*******",
        "namespace_name": "reportportal",
        "pod_id": "******-****-***-****-****",
        "host": "ip-**-**-**-****.ec2.internal",
        "container_name": "api",
        "docker_id": "********************************,
        "container_hash": "docker.io/reportportal/service-api@sha256:*************************",
        "container_image": "docker.io/reportportal/service-api:5.14.4"
    }
}`
`{
    "time": "2025-11-13T17:50:00.015562918Z",
    "stream": "stdout",
    "_p": "F",
    "log": "org.springframework.core.task.TaskRejectedException: ExecutorService in active state did not accept task: org.springframework.aop.interceptor.AsyncExecutionInterceptor$$Lambda/0x00007fbb996d5310@6f3bfec9",
    kubernetes": {
        "pod_name": "reportportal-api-*******",
        "namespace_name": "reportportal",
        "pod_id": "******-****-***-****-****",
        "host": "ip-**-**-**-****.ec2.internal",
        "container_name": "api",
        "docker_id": "********************************,
        "container_hash": "docker.io/reportportal/service-api@sha256:*************************",
        "container_image": "docker.io/reportportal/service-api:5.14.4"
    }
}`
Above are sample logs we found before losing the DB connection.

**Comment by heilwood** [comment]
i think this bug has been fixed
