### ISSUE TITLE
Azure SAML Login Issue with Redirect URI

### ISSUE THREAD

**Issue by begemotik** [reportportal/reportportal#2558]
**Describe the bug**
While being authenticated using Azure SAML integration the following error occurs on the https://login.microsoftonline.com page (notice **http schema** in the URL):
```
AADSTS50011: The reply URL 'http://<domain>/uat/login/saml2/sso/AzureSAML' specified in the request does not match the reply URLs configured for the application 'report.portal.sp.id'. Make sure the reply URL sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/urlMismatchError to learn more about how to fix this.
```
The RP is deployed in the Kubernetes cluster, exposed via NGINX Ingress Controller, TLS is offloaded on AWS NLB.

The integration is configured according to the documentation pieces:
- https://reportportal.io/docs/plugins/authorization/SamlProviders/Overview
- https://reportportal.io/docs/plugins/authorization/SamlProviders/AzureSaml (updated URL to `https://<host>/uat/login/saml2/sso/{your-provider-name}`)

[There is an open question in the Discussions](https://github.com/reportportal/reportportal/discussions/2555).

**Expected behavior**
Login with SAML without problem.

**Versions:**
 - OS, Browser - MacOS, Chromium
 - Version of RP - 5.14.1
 - Installed with Helm chart 25.5.30

---

Please let me know if any additional information is required. Thank you.

**Comment by Pink-Bumblebee** [comment]
Hello @begemotik , we've released fix for this issue : https://github.com/reportportal/service-authorization/issues/382#issuecomment-2955968778. Please use it.
Also please use this information from Release Notes:
`Action Required 3 - Update your SAML integration: Please update your existing SAML integration to use the new standard callback URL format: /login/saml2/sso/{saml-provider-name} This ensures compatibility with the latest updates and improved security practices.`
Sorry for inconvenience.

**Comment by begemotik** [comment]
I'm afraid it didn't help. I've used the recent Helm chart - [25.6.9](https://github.com/reportportal/kubernetes/tree/reportportal-25.6.9/reportportal) to make sure service-authorization 5.14.1 is used.

If `/login/saml2/sso/{saml-provider-name}` provided the auth process doesn't follow the redirects and stuck in `/uat/login` page

![Image](https://github.com/user-attachments/assets/e3efdb42-2b36-48a5-b521-6d23e7e09e83)

With `/uat/login/saml2/sso/{your-provider-name}` the issue persists.

---

Additionally I'd like to note that [SAML Overview page](https://reportportal.io/docs/plugins/authorization/SamlProviders/Overview/#reportportal-assertion-consumer-service-url) implies using prefix `/uat` in the URI, whereas [Azure SAML page](https://reportportal.io/docs/plugins/authorization/SamlProviders/AzureSaml) doesn't say anything about the new path (since 5.14.0) that is used for SAML configuration.

**Comment by begemotik** [comment]
**Additional context to the issue**

We have Nginx Ingress Controller behind AWS NLB. TLS is terminated on the NLB and plain http traffic is directed to http port of NGINX. I expect that if we terminated TLS on Ingress Controller we would not face the issue since the correct `X-Forwarded-*` headers would be passed to the application, but unfortunately it's not possible for our setup as it triggers huge reconfiguration for the existing Ingresses.

As it was stated in [this comment](https://github.com/reportportal/reportportal/discussions/2555#discussioncomment-13419041) somehow it was working fine before 25.1.0 release. 

---

Additionally, I tried exposing RP via AWS Load Balancer Controller (L7) without NGINX and Azure SAML **works** in that case (correct `X-Forwarded-*` headers passed), but some functionality of RP itself is broken, which refers me to [some other issue](https://github.com/reportportal/reportportal/issues/2554).

```
2025-06-11T18:27:35.069Z ERROR 1 --- [api] [nio-8585-exec-6] c.e.r.r.c.e.rest.DefaultErrorResolver    : Could not create URI object: Expected scheme-specific part at index 6: https:

java.lang.IllegalStateException: Could not create URI object: Expected scheme-specific part at index 6: https:
```

**Comment by Juliet-2011** [comment]
The fix didn't help on our side either — we still can't log in with the current version.
Unfortunately, reverting to an older version isn't an option for us, as we are unable to upload the unit test results with it.

Are there any ideas or potential solutions you can suggest to resolve this issue while staying on the latest version?

**Comment by AlenSiilivask** [comment]
Hello @Pink-Bumblebee, is there any progress with this issue? Have the same issue.

**Comment by Pink-Bumblebee** [comment]
@AlenSiilivask , please check this issue (and solution) https://github.com/reportportal/service-api/issues/2310. Maybe it will be helpful. 
Also, today we released Component Update (so-called version 25.1.2).

**Comment by Juliet-2011** [comment]
@Pink-Bumblebee  That still doesn’t solve the issue, unfortunately.

**Comment by Pink-Bumblebee** [comment]
@Juliet-2011 , could you please be more informative? What doesn't solved: newer version or settings in Ingress controller?

**Comment by Juliet-2011** [comment]
Yes, sorry. 
Both not. We tried the newest version and made an update of SAML Plugin. But the redirect URL is still http instead of https.

![Image](https://github.com/user-attachments/assets/7a00f14d-ee98-4791-8d68-301a15f7be61)

**Comment by Pink-Bumblebee** [comment]
Http?? As I see here https://reportportal.io/docs/plugins/authorization/SamlProviders/Overview#set-up-connection maybe it should be https? I'm not so familiar with Azure SAML, but I think that logs of uat and api services could give some keys.

**Comment by Juliet-2011** [comment]
Our configuration is correct – we did not encounter any issues before the update.
Previously, we used HELM Chart version 25.4.10 (see discussion: [GitHub Issue #2555](https://github.com/reportportal/reportportal/discussions/2555)).
With the update to the latest version, we also adjusted the UAT path according to the official documentation:
➡️ [ReportPortal SAML Setup Documentation](https://reportportal.io/docs/plugins/authorization/SamlProviders/Overview#set-up-connection)

**Comment by badrinrs** [comment]
We see the same error on ReportPortal v25.1.4

I see the stacktrace in uat as below

```java
reportportal-uat-1  | org.springframework.security.saml2.Saml2Exception: java.io.FileNotFoundException: https://login.microsoftonline.com/00fc7e42-ad65-4c4c-ab54-848ba124a5b7/federationmetadata[%E2%80%A6]nmetadata.xml?appid=d043c73f-0f23-410c-99d5-881fa33ca2d2
reportportal-uat-1  |   at org.springframework.security.saml2.provider.service.registration.RelyingPartyRegistrations.fromMetadataLocation(RelyingPartyRegistrations.java:86) ~[spring-security-saml2-service-provider-6.4.2.jar!/:6.4.2]
reportportal-uat-1  |   at com.epam.reportportal.auth.integration.handler.impl.strategy.SamlIntegrationStrategy.populateProviderDetails(SamlIntegrationStrategy.java:112) ~[!/:5.14.2]
reportportal-uat-1  |   at com.epam.reportportal.auth.integration.handler.impl.strategy.SamlIntegrationStrategy.save(SamlIntegrationStrategy.java:101) ~[!/:5.14.2]
reportportal-uat-1  |   at com.epam.reportportal.auth.integration.handler.impl.strategy.AuthIntegrationStrategy.createIntegration(AuthIntegrationStrategy.java:59) ~[!/:5.14.2]
reportportal-uat-1  |   at com.epam.reportportal.auth.integration.handler.impl.CreateAuthIntegrationHandlerImpl.createAuthIntegration(CreateAuthIntegrationHandlerImpl.java:68) ~[!/:5.14.2]
reportportal-uat-1  |   at com.epam.reportportal.auth.endpoint.AuthConfigurationEndpoint.createAuthIntegration(AuthConfigurationEndpoint.java:84) ~[!/:5.14.2]
reportportal-uat-1  |   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
reportportal-uat-1  |   at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
reportportal-uat-1  |   at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359) ~[spring-aop-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:380) ~[spring-tx-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:727) ~[spring-aop-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at com.epam.reportportal.auth.endpoint.AuthConfigurationEndpoint$$SpringCGLIB$$0.createAuthIntegration(<generated>) ~[!/:5.14.2]
reportportal-uat-1  |   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
reportportal-uat-1  |   at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
reportportal-uat-1  |   at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:258) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:191) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:986) ~[spring-webmvc-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:891) ~[spring-webmvc-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:653) ~[jakarta.servlet-api-6.1.0.jar!/:6.1.0]
reportportal-uat-1  |   at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:723) ~[jakarta.servlet-api-6.1.0.jar!/:6.1.0]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:101) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.oauth2.client.web.OAuth2AuthorizationCodeGrantFilter.doFilterInternal(OAuth2AuthorizationCodeGrantFilter.java:183) ~[spring-security-oauth2-client-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:145) ~[spring-security-oauth2-resource-server-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter.doFilterInternal(DefaultLogoutPageGeneratingFilter.java:58) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:220) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:206) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.authentication.ui.DefaultResourcesFilter.doFilter(DefaultResourcesFilter.java:72) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:198) ~[spring-security-oauth2-client-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:198) ~[spring-security-oauth2-client-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:243) ~[spring-webmvc-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:238) ~[spring-security-config-6.4.4.jar!/:6.4.4]
reportportal-uat-1  |   at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:362) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:278) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:114) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:116) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:732) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:398) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:903) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1189) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:658) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.40.jar!/:na]
reportportal-uat-1  |   at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
reportportal-uat-1  | Caused by: java.io.FileNotFoundException: https://login.microsoftonline.com/00fc7e42-ad65-4c4c-ab54-848ba124a5b7/federationmetadata[%E2%80%A6]nmetadata.xml?appid=d043c73f-0f23-410c-99d5-881fa33ca2d2
reportportal-uat-1  |   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2009) ~[na:na]
reportportal-uat-1  |   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614) ~[na:na]
reportportal-uat-1  |   at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[na:na]
reportportal-uat-1  |   at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:233) ~[spring-core-6.2.5.jar!/:6.2.5]
reportportal-uat-1  |   at org.springframework.security.saml2.provider.service.registration.RelyingPartyRegistrations.fromMetadataLocation(RelyingPartyRegistrations.java:79) ~[spring-security-saml2-service-provider-6.4.2.jar!/:6.4.2]
reportportal-uat-1  |   ... 177 common frames omitted
```

**Comment by raikbitters** [comment]
Hi @badrinrs . That's not the same. The metadata URL in your log is invalid:

![Image](https://github.com/user-attachments/assets/10ed76f2-605a-40be-b251-18ac91f78e20)

The reportportal-uat service can't retrieve it.

**Comment by Pink-Bumblebee** [comment]
Hello @begemotik  and @Juliet-2011. We released new version of uat service (5.14.3), so could you please check on your side whether your issues were resolved?

**Comment by begemotik** [comment]
Hello @Pink-Bumblebee, I've updated to recent Helm chart version (it includes uat service 5.14.3) and unfortunately the result is the same.

> AADSTS50011: The reply URL 'http://\<domain\>/uat/login/saml2/sso/azure-saml' specified in the request does not match the reply URLs configured for the application 'report.portal.sp.id'.

**Comment by AlenSiilivask** [comment]
Updated to the recent helm chart, and for some reason i get the strange port:80 in the end. - 
`AADSTS50011: The reply URL 'https://<domain>:80/uat/login/saml2/sso/Reportportal' specified in the request does not match the reply URLs configured for the application 'report.portal.sp.id'.`

**Comment by Pink-Bumblebee** [comment]
@raikbitters , could you please check?

**Comment by Juliet-2011** [comment]
We already performed the update on Monday, but the error message remained the same. Then we set the x-forwarded-Proto: "https" customRequestHeader and encountered the issue with port :80. 
We managed to resolve that issue with the additional header x-forwarded-port: "".

Now, we can log in via SAML again, but only **once** — or rather, only if the user does not yet exist. After that, we get the following error in the URL:
...ui/#login?errorAuth=User%20with%20email%20'<email@address.com>'%20already%20exists
The error does not appear in the browser console, only in the URL.

**Comment by AlenSiilivask** [comment]
Hello, we tried every posted solution and for us the port :80 is still present.

**Comment by raikbitters** [comment]
@Juliet-2011 hello. Could you specify the Service Auth version? Moreover, check if you have any users with uppercase email addresses. If so, you will need to change their email addresses to lowercase or install the latest Service Auth. We fixed case sensitive in the latest fix.

**Comment by Juliet-2011** [comment]
@raikbitters Hi. Yes, of course. The Service Auth = 5.14.3. Everything deployed with the Helm Chart 25.7.3. So latest version. 
But we have also only lowerCase email addresses.

**Comment by begemotik** [comment]
Hello,

As we expected in [that comment](https://github.com/reportportal/reportportal/issues/2558#issuecomment-2963851335) enabling https on the NGINX Ingress Controller allowed the header which RP expects to be passed correctly.

**Comment by Pink-Bumblebee** [comment]
@begemotik , so, have you resolved your issue?
BTW, today I've got another "silver bullet" from dev team : it is need to add to service-api and service-authorization as environment variable - SERVER_FORWARD_HEADERS_STRATEGY=FRAMEWORK (for docker-based installation).

**Comment by begemotik** [comment]
Yes, we've resolved the issue for SAML. The variables you are mentioning look indeed promising. IMO, it might be worth adding to the documentation somewhere.

**Comment by rmartins-nos** [comment]
I am using helm chart (25.7.3) to deploy to kubernetes (GCP), can anyone help what are the settings in values.yaml to solve this issue?

**Comment by hlebkanonik** [comment]
@rmartins-nos, Hi! In the current **25.8.8** helm chart release (Reportportal 25.1.6), this issue is fixed, and `SERVER_FORWARD_HEADERS_STRATEGY=FRAMEWORK` is enabled by default. 

For **25.7.3**, you can try passing this environment using `extraEnvs` in both the API and UAT (authorization) services.

**Comment by Idosegal** [comment]
@hlebkanonik Im still facing same issue. Im getting an error:

AADSTS50011: The reply URL 'http://report-portal-dev.ty.com/uat/login/saml2/sso/Test_SAML' specified in the request does not match the reply URLs configured for the application 'report.portal.sp.id'. Make sure the reply URL sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/urlMismatchError to learn more about how to fix this.

I noticed for the http in the request, but it's https configured in the SAML integration. What can be the cause for this issue?
