### ISSUE TITLE
Unable to create tickets from report portal for few projects #103

### ISSUE THREAD

**Issue by iamansaxena** [reportportal/reportportal#2633]
**Describe the bug**
I'm unable to create a jira bug ticket from report portal in jira though I'm able to create it from the JIra UI using same details

Everytime I try to create a ticket via Report Portal, I'm getting the following errors at the API pods:
"2025-09-19T12:31:43.098Z ERROR 1 --- [api] [nio-8585-exec-8] c.e.r.e.jira.command.PostTicketCommand : 400 Bad Request on POST request for "https://sprinklr.atlassian.net/rest/api/latest/issue": "{"errorMessages":[],"errors":{"fixVersions":"Version id '26.1' is not valid"}}"
2025-09-19T12:31:43.099Z ERROR 1 --- [api] [nio-8585-exec-8] .e.t.r.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Impossible interact with integration.
".

Interestingly, for few project where only basic common fields are being useed, I'm able to create but my actual projects are using a lot of custom fields and drop down where this is failing.

Plugin version: V5.13.5
Report Portal Version: 25.1.9

API Payload from Report Portal:
{ "projectId": 2, "entity": { "includeComments": true, "includeData": true, "includeLogs": true, "logQuantity": 50, "item": 52621, "fields": [ { "id": "issuetype", "value": [ "Bug" ], "required": true, "fieldName": "Issue Type", "fieldType": "issuetype", "definedValues": [], "disabled": true }, { "id": "customfield_19203", "value": [ "UI" ], "required": true, "fieldName": "Issue Category", "fieldType": "option", "definedValues": [ { "valueId": "32269", "valueName": "AI" }, { "valueId": "27400", "valueName": "Backend" }, { "valueId": "30444", "valueName": "Backend & UI" }, { "valueId": "33844", "valueName": "ITOPS" }, { "valueId": "32270", "valueName": "Mobile" }, { "valueId": "29501", "valueName": "Not Applicable" }, { "valueId": "27401", "valueName": "UI" }, { "valueId": "34071", "valueName": "RED" }, { "valueId": "34127", "valueName": "Product" }, { "valueId": "34128", "valueName": "Channel" }, { "valueId": "35212", "valueName": "Backend+AI" }, { "valueId": "35213", "valueName": "UI+Backend+AI" }, { "valueId": "69724", "valueName": "UI+AI" } ] }, { "id": "fixVersions", "required": true, "fieldName": "Fix versions", "fieldType": "array", "definedValues": [ { "valueId": "43810", "valueName": "20.7.1_Bug_L3" }, { "valueId": "20867", "valueName": "SmartCare 1.0" }, { "valueId": "25003", "valueName": "10.3.0 " }, { "valueId": "25004", "valueName": "10.4.0" }, { "valueId": "25707", "valueName": "Parking Lot" }, { "valueId": "25812", "valueName": "11.0" }, { "valueId": "25909", "valueName": "11.1" }, { "valueId": "26200", "valueName": "11.2" }, { "valueId": "27102", "valueName": "11.3" }, { "valueId": "28100", "valueName": "11.1.4" }, { "valueId": "28200", "valueName": "11.1.3" }, { "valueId": "28512", "valueName": "11.2.1" }, { "valueId": "29300", "valueName": "11.4" }, { "valueId": "30001", "valueName": "11.3.5_Minor" }, { "valueId": "30202", "valueName": "11.2.5_Minor" }, { "valueId": "31500", "valueName": "11.5" }, { "valueId": "31501", "valueName": "11.3.1" }, { "valueId": "31505", "valueName": "11.3.3" }, { "valueId": "31700", "valueName": "11.3.6" }, { "valueId": "31701", "valueName": "11.3.5" }, { "valueId": "31704", "valueName": "12.1" }, { "valueId": "31712", "valueName": "11.3.2" }, { "valueId": "32201", "valueName": "11.3.4" }, { "valueId": "32304", "valueName": "11.3.8" }, { "valueId": "33201", "valueName": "11.3.9" }, { "valueId": "33300", "valueName": "11.4.2" }, { "valueId": "33401", "valueName": "11.4.1" }, { "valueId": "34001", "valueName": "12.2" }, { "valueId": "34002", "valueName": "11.4.3" }, { "valueId": "35600", "valueName": "11.4.5" }, { "valueId": "35702", "valueName": "11.4.4" }, { "valueId": "35813", "valueName": "11.4.8" }, { "valueId": "35832", "valueName": "12.1.1" }, { "valueId": "35833", "valueName": "12.1.2" }, { "valueId": "35834", "valueName": "11.4.6" }, { "valueId": "35837", "valueName": "11.4.10" }, { "valueId": "35866", "valueName": "12.1.3" }, { "valueId": "35874", "valueName": "12.3" }, { "valueId": "35876", "valueName": "12.1.4" }, { "valueId": "35906", "valueName": "12.2.1" }, { "valueId": "35912", "valueName": "12.2.2" }, { "valueId": "35930", "valueName": "12.2.3" }, { "valueId": "35935", "valueName": "12.4" }, { "valueId": "35942", "valueName": "12.2.4" }, { "valueId": "35976", "valueName": "12.3.1" }, { "valueId": "35980", "valueName": "12.3.7" }, { "valueId": "35988", "valueName": "12.3.3" }, { "valueId": "35999", "valueName": "12.3.5" }, { "valueId": "36003", "valueName": "12.3.2" }, { "valueId": "36006", "valueName": "12.5" }, { "valueId": "36030", "valueName": "14.1" }, { "valueId": "36040", "valueName": "12.5.1" }, { "valueId": "36121", "valueName": "14.2 - TBD" }, { "valueId": "36139", "valueName": "14.4" }, { "valueId": "36140", "valueName": "14.7" }, { "valueId": "36141", "valueName": "14.11" }, { "valueId": "36186", "valueName": "14.2" }, { "valueId": "36191", "valueName": "14.3" }, { "valueId": "36216", "valueName": "14.5" }, { "valueId": "36247", "valueName": "14.6" }, { "valueId": "36248", "valueName": "14.8" }, { "valueId": "36249", "valueName": "14.9" }, { "valueId": "36250", "valueName": "14.10" }, { "valueId": "36286", "valueName": "14..11" }, { "valueId": "36390", "valueName": "14.12" }, { "valueId": "36391", "valueName": "15.1" }, { "valueId": "36392", "valueName": "15.2" }, { "valueId": "36393", "valueName": "15.3" }, { "valueId": "36394", "valueName": "15.4" }, { "valueId": "36395", "valueName": "15.5" }, { "valueId": "36396", "valueName": "15.6" }, { "valueId": "36397", "valueName": "15.7" }, { "valueId": "36398", "valueName": "15.8" }, { "valueId": "36400", "valueName": "15.11" }, { "valueId": "36401", "valueName": "16.2" }, { "valueId": "36587", "valueName": "15.9" }, { "valueId": "36588", "valueName": "15.4.5" }, { "valueId": "36602", "valueName": "15.11_Voice" }, { "valueId": "36627", "valueName": "16.2_Voice" }, { "valueId": "36648", "valueName": "16.4" }, { "valueId": "36649", "valueName": "16.5" }, { "valueId": "36674", "valueName": "16.6" }, { "valueId": "36675", "valueName": "16.7" }, { "valueId": "36676", "valueName": "16.8" }, { "valueId": "36677", "valueName": "16.9" }, { "valueId": "36678", "valueName": "16.10" }, { "valueId": "36772", "valueName": "16.10_Hdfc" }, { "valueId": "36825", "valueName": "17.1" }, { "valueId": "36780", "valueName": "17.4" }, { "valueId": "36837", "valueName": "17.4_Hdfc" }, { "valueId": "36838", "valueName": "17.7" }, { "valueId": "36839", "valueName": "17.10" }, { "valueId": "36862", "valueName": "18.2" }, { "valueId": "36936", "valueName": "Roadmap" }, { "valueId": "37979", "valueName": "18.5" }, { "valueId": "37980", "valueName": "18.8" }, { "valueId": "37981", "valueName": "18.11" }, { "valueId": "38042", "valueName": "19.2" }, { "valueId": "38043", "valueName": "19.5" }, { "valueId": "38044", "valueName": "19.8" }, { "valueId": "38045", "valueName": "19.11" }, { "valueId": "39127", "valueName": "19.8.1" }, { "valueId": "39158", "valueName": "19.11_mobile" }, { "valueId": "39162", "valueName": "19.8.1_Bug_L3" }, { "valueId": "39163", "valueName": "19.8.1_Regression" }, { "valueId": "39207", "valueName": "19.11_Bug_L3" }, { "valueId": "39208", "valueName": "19.11_Regression" }, { "valueId": "39276", "valueName": "20.2" }, { "valueId": "39280", "valueName": "19.11.1" }, { "valueId": "39281", "valueName": "19.11.1_Bug_L3" }, { "valueId": "39282", "valueName": "19.11.1_Regression" }, { "valueId": "39286", "valueName": "20.2_Bug_L3" }, { "valueId": "39287", "valueName": "20.2_Regression" }, { "valueId": "39417", "valueName": "Release_Backlog" }, { "valueId": "39441", "valueName": "20.4" }, { "valueId": "39442", "valueName": "20.4_Bug_L3" }, { "valueId": "39443", "valueName": "20.4_Regression" }, { "valueId": "39552", "valueName": "20.7" }, { "valueId": "39553", "valueName": "20.10" }, { "valueId": "39595", "valueName": "26.1" }, { "valueId": "39616", "valueName": "20.1.02" }, { "valueId": "39683", "valueName": "20.2.1" }, { "valueId": "39684", "valueName": "20.2.1_Bug_L3" }, { "valueId": "39717", "valueName": "20.1.03" }, { "valueId": "39788", "valueName": "20.1.04" }, { "valueId": "39891", "valueName": "20.4_Top_Value_Drivers" }, { "valueId": "40080", "valueName": "20.2.1_Regression" }, { "valueId": "40101", "valueName": "20.2_Customer_Issue" }, { "valueId": "40115", "valueName": "Incorrect_Fix_Version" }, { "valueId": "42148", "valueName": "20.4.1" }, { "valueId": "42248", "valueName": "20.7_Bug_L3" }, { "valueId": "42281", "valueName": "20.4.1_Bug_L3" }, { "valueId": "43282", "valueName": "20.4.1_Regression" }, { "valueId": "43315", "valueName": "26.4" }, { "valueId": "43316", "valueName": "26.7" }, { "valueId": "43317", "valueName": "26.10" }, { "valueId": "43639", "valueName": "20.7.1" }, { "valueId": "43773", "valueName": "20.7_Regression" }, { "valueId": "43809", "valueName": "20.10_Bug_L3" }, { "valueId": "44622", "valueName": "20.10_Regression" }, { "valueId": "44689", "valueName": "20.7.1_Regression" }, { "valueId": "45278", "valueName": "26.1_Bug_L3" }, { "valueId": "45824", "valueName": "26.1_Regression" }, { "valueId": "46227", "valueName": "Test12.3" }, { "valueId": "46342", "valueName": "test_FixVersion_20.00" } ], "value": [ "20.10_Regression" ] }, { "id": "customfield_22928", "value": [ "No" ], "required": true, "fieldName": "Is KB Documentation  Required?", "fieldType": "option", "definedValues": [ { "valueId": "60843", "valueName": "Yes, Release Notes" }, { "valueId": "60844", "valueName": "Yes, Article" }, { "valueId": "60845", "valueName": "Yes,Release Notes + Article" }, { "valueId": "60066", "valueName": "No" } ] }, { "id": "customfield_18501", "required": true, "fieldName": "Functional Solution", "fieldType": "array", "definedValues": [ { "valueId": "26208", "valueName": "Advertising" }, { "valueId": "31072", "valueName": "Advocacy" }, { "valueId": "64111", "valueName": "AI" }, { "valueId": "31273", "valueName": "Benchmarking" }, { "valueId": "26210", "valueName": "Care" }, { "valueId": "68728", "valueName": "Certificates" }, { "valueId": "60267", "valueName": "CFM" }, { "valueId": "34162", "valueName": "CXMW - (HDFC CRM)" }, { "valueId": "31093", "valueName": "Display" }, { "valueId": "34010", "valueName": "Distributed" }, { "valueId": "68730", "valueName": "Elastic-Search" }, { "valueId": "26212", "valueName": "Engagement" }, { "valueId": "32513", "valueName": "Hyperspace Design System" }, { "valueId": "30629", "valueName": "Incubation/Platform" }, { "valueId": "31073", "valueName": "Integrations" }, { "valueId": "30628", "valueName": "Intuition" }, { "valueId": "33626", "valueName": "IT Team" }, { "valueId": "32062", "valueName": "ITOPS" }, { "valueId": "26207", "valueName": "Marketing" }, { "valueId": "31084", "valueName": "Mobile" }, { "valueId": "68729", "valueName": "Mongo" }, { "valueId": "32435", "valueName": "RED" }, { "valueId": "26209", "valueName": "Research" }, { "valueId": "61026", "valueName": "Security" }, { "valueId": "32039", "valueName": "Self Serve" }, { "valueId": "34121", "valueName": "Voice Telephony" } ], "value": [ "Care" ] }, { "id": "issuelinks", "required": true, "fieldName": "Linked Issues", "fieldType": "array", "definedValues": [], "value": [ "CARE-86846" ] }, { "id": "description", "required": true, "fieldName": "Description", "fieldType": "string", "definedValues": [], "value": [ "Report Portal" ] }, { "id": "summary", "required": true, "fieldName": "Summary", "fieldType": "string", "definedValues": [], "value": [ "Report Portal" ] }, { "id": "customfield_18800", "value": [ "Yes" ], "required": true, "fieldName": "Caught by Automation", "fieldType": "option", "definedValues": [ { "valueId": "26700", "valueName": "Yes" }, { "valueId": "26701", "valueName": "No" } ] }, { "id": "customfield_22858", "value": [ "Low" ], "required": true, "fieldName": "Severity", "fieldType": "option", "definedValues": [ { "valueId": "58346", "valueName": "Low" }, { "valueId": "58347", "valueName": "Medium" }, { "valueId": "58348", "valueName": "High" }, { "valueId": "58349", "valueName": "Critical" } ] } ], "backLinks": { "52621": "https://reportportal.sprinklr.com/ui/#default_personal/launches/all/789/52604/52605/52621/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED" } } }

API Payload from JIRA UI
{ "fields": { "project": { "id": "15561" }, "issuetype": { "id": "28" }, "summary": "Dummy Bug | Report Portal", "priority": { "id": "5", "name": "Trivial", "iconUrl": "https://sprinklr.atlassian.net/images/icons/priorities/trivial_new.svg" }, "customfield_22858": { "id": "58346", "value": "Low" }, "customfield_18501": [ { "id": "26210", "value": "Care" } ], "customfield_19203": { "id": "27401", "value": "UI" }, "fixVersions": [ { "id": "44622" } ], "assignee": { "id": "712020:6e4505aa-185e-4557-aa33-50f524e93128" }, "description": { "version": 1, "type": "doc", "content": [ { "type": "paragraph", "content": [ { "type": "text", "text": "Report Portal" } ] } ] }, "customfield_19500": { "type": "doc", "version": 1, "content": [ { "type": "paragraph", "content": [ { "type": "text", "text": "Not Applicable. " } ] } ] }, "customfield_15014": [ { "id": "18023", "value": "ALL" } ], "customfield_18800": { "id": "26700", "value": "Yes" }, "customfield_20013": [], "customfield_20103": [], "customfield_15018": [], "components": [], "customfield_13971": [], "labels": [], "customfield_20102": [], "customfield_15019": [], "customfield_15170": [], "customfield_13972": [], "customfield_17600": [], "customfield_20498": [], "customfield_21675": [], "customfield_22878": [], "customfield_27722": [], "customfield_22928": { "id": "60066", "value": "No" }, "customfield_26319": [ { "id": "65024", "value": "NA" } ], "customfield_14670": [], "customfield_18500": [ { "id": "66068", "value": "QA6" } ], "customfield_22778": [ { "id": "55684", "value": "Sprinklr" } ] }, "update": { "issuelinks": [ { "add": { "values": [ { "type": { "id": "12042" }, "inwardIssues": [ { "key": "CARE-86846" } ] } ] } } ] }, "watchers": [ "712020:6e4505aa-185e-4557-aa33-50f524e93128" ], "externalToken": "0.643655902473256" }

**Expected behavior**
I should be able to log jira bugs even though there's a lot of custom fields
**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP 

<img width="415" height="99" alt="Image" src="https://github.com/user-attachments/assets/1ded800e-d24c-42dc-b44c-9786f8017770" />

**Comment by Pink-Bumblebee** [comment]
Looks like it is a copy of https://github.com/reportportal/plugin-bts-jira-cloud/issues/103.

We released newer version 25.1.12 of ReportPortal with newer version of plugin-bts-jira-cloud 5.13.7. Could you please check it?

**Comment by iamansaxena** [comment]
Hi @Pink-Bumblebee  We have just upgraded but still facing the same issue. 


Here's the request /postTicket `"{
    "projectId": 2,
    "entity": {
        "includeComments": true,
        "includeData": true,
        "includeLogs": true,
        "logQuantity": 50,
        "item": 1292027,
        "fields": [
            {
                "id": "issuetype",
                "value": [
                    "Bug"
                ],
                "required": true,
                "fieldName": "Issue Type",
                "fieldType": "issuetype",
                "definedValues": [],
                "disabled": true
            },
            {
                "id": "customfield_19203",
                "value": [
                    "UI"
                ],
                "required": true,
                "fieldName": "Issue Category",
                "fieldType": "option",
                "definedValues": [
                    {
                        "valueId": "32269",
                        "valueName": "AI"
                    },
                    {
                        "valueId": "27400",
                        "valueName": "Backend"
                    },
                    {
                        "valueId": "30444",
                        "valueName": "Backend & UI"
                    },
                    {
                        "valueId": "33844",
                        "valueName": "ITOPS"
                    },
                    {
                        "valueId": "32270",
                        "valueName": "Mobile"
                    },
                    {
                        "valueId": "29501",
                        "valueName": "Not Applicable"
                    },
                    {
                        "valueId": "27401",
                        "valueName": "UI"
                    },
                    {
                        "valueId": "34071",
                        "valueName": "RED"
                    },
                    {
                        "valueId": "34127",
                        "valueName": "Product"
                    },
                    {
                        "valueId": "34128",
                        "valueName": "Channel"
                    },
                    {
                        "valueId": "35212",
                        "valueName": "Backend+AI"
                    },
                    {
                        "valueId": "35213",
                        "valueName": "UI+Backend+AI"
                    },
                    {
                        "valueId": "69724",
                        "valueName": "UI+AI"
                    },
                    {
                        "valueId": "71224",
                        "valueName": "Zephyr"
                    }
                ]
            },
            {
                "id": "fixVersions",
                "required": true,
                "fieldName": "Fix versions",
                "fieldType": "array",
                "definedValues": [
                    {
                        "valueId": "43810",
                        "valueName": "20.7.1_Bug_L3"
                    },
                    {
                        "valueId": "20867",
                        "valueName": "SmartCare 1.0"
                    },
                    {
                        "valueId": "25003",
                        "valueName": "10.3.0 "
                    },
                    {
                        "valueId": "25004",
                        "valueName": "10.4.0"
                    },
                    {
                        "valueId": "25707",
                        "valueName": "Parking Lot"
                    },
                    {
                        "valueId": "25812",
                        "valueName": "11.0"
                    },
                    {
                        "valueId": "25909",
                        "valueName": "11.1"
                    },
                    {
                        "valueId": "26200",
                        "valueName": "11.2"
                    },
                    {
                        "valueId": "27102",
                        "valueName": "11.3"
                    },
                    {
                        "valueId": "28100",
                        "valueName": "11.1.4"
                    },
                    {
                        "valueId": "28200",
                        "valueName": "11.1.3"
                    },
                    {
                        "valueId": "28512",
                        "valueName": "11.2.1"
                    },
                    {
                        "valueId": "29300",
                        "valueName": "11.4"
                    },
                    {
                        "valueId": "30001",
                        "valueName": "11.3.5_Minor"
                    },
                    {
                        "valueId": "30202",
                        "valueName": "11.2.5_Minor"
                    },
                    {
                        "valueId": "31500",
                        "valueName": "11.5"
                    },
                    {
                        "valueId": "31501",
                        "valueName": "11.3.1"
                    },
                    {
                        "valueId": "31505",
                        "valueName": "11.3.3"
                    },
                    {
                        "valueId": "31700",
                        "valueName": "11.3.6"
                    },
                    {
                        "valueId": "31701",
                        "valueName": "11.3.5"
                    },
                    {
                        "valueId": "31704",
                        "valueName": "12.1"
                    },
                    {
                        "valueId": "31712",
                        "valueName": "11.3.2"
                    },
                    {
                        "valueId": "32201",
                        "valueName": "11.3.4"
                    },
                    {
                        "valueId": "32304",
                        "valueName": "11.3.8"
                    },
                    {
                        "valueId": "33201",
                        "valueName": "11.3.9"
                    },
                    {
                        "valueId": "33300",
                        "valueName": "11.4.2"
                    },
                    {
                        "valueId": "33401",
                        "valueName": "11.4.1"
                    },
                    {
                        "valueId": "34001",
                        "valueName": "12.2"
                    },
                    {
                        "valueId": "34002",
                        "valueName": "11.4.3"
                    },
                    {
                        "valueId": "35600",
                        "valueName": "11.4.5"
                    },
                    {
                        "valueId": "35702",
                        "valueName": "11.4.4"
                    },
                    {
                        "valueId": "35813",
                        "valueName": "11.4.8"
                    },
                    {
                        "valueId": "35832",
                        "valueName": "12.1.1"
                    },
                    {
                        "valueId": "35833",
                        "valueName": "12.1.2"
                    },
                    {
                        "valueId": "35834",
                        "valueName": "11.4.6"
                    },
                    {
                        "valueId": "35837",
                        "valueName": "11.4.10"
                    },
                    {
                        "valueId": "35866",
                        "valueName": "12.1.3"
                    },
                    {
                        "valueId": "35874",
                        "valueName": "12.3"
                    },
                    {
                        "valueId": "35876",
                        "valueName": "12.1.4"
                    },
                    {
                        "valueId": "35906",
                        "valueName": "12.2.1"
                    },
                    {
                        "valueId": "35912",
                        "valueName": "12.2.2"
                    },
                    {
                        "valueId": "35930",
                        "valueName": "12.2.3"
                    },
                    {
                        "valueId": "35935",
                        "valueName": "12.4"
                    },
                    {
                        "valueId": "35942",
                        "valueName": "12.2.4"
                    },
                    {
                        "valueId": "35976",
                        "valueName": "12.3.1"
                    },
                    {
                        "valueId": "35980",
                        "valueName": "12.3.7"
                    },
                    {
                        "valueId": "35988",
                        "valueName": "12.3.3"
                    },
                    {
                        "valueId": "35999",
                        "valueName": "12.3.5"
                    },
                    {
                        "valueId": "36003",
                        "valueName": "12.3.2"
                    },
                    {
                        "valueId": "36006",
                        "valueName": "12.5"
                    },
                    {
                        "valueId": "36030",
                        "valueName": "14.1"
                    },
                    {
                        "valueId": "36040",
                        "valueName": "12.5.1"
                    },
                    {
                        "valueId": "36121",
                        "valueName": "14.2 - TBD"
                    },
                    {
                        "valueId": "36139",
                        "valueName": "14.4"
                    },
                    {
                        "valueId": "36140",
                        "valueName": "14.7"
                    },
                    {
                        "valueId": "36141",
                        "valueName": "14.11"
                    },
                    {
                        "valueId": "36186",
                        "valueName": "14.2"
                    },
                    {
                        "valueId": "36191",
                        "valueName": "14.3"
                    },
                    {
                        "valueId": "36216",
                        "valueName": "14.5"
                    },
                    {
                        "valueId": "36247",
                        "valueName": "14.6"
                    },
                    {
                        "valueId": "36248",
                        "valueName": "14.8"
                    },
                    {
                        "valueId": "36249",
                        "valueName": "14.9"
                    },
                    {
                        "valueId": "36250",
                        "valueName": "14.10"
                    },
                    {
                        "valueId": "36286",
                        "valueName": "14..11"
                    },
                    {
                        "valueId": "36390",
                        "valueName": "14.12"
                    },
                    {
                        "valueId": "36391",
                        "valueName": "15.1"
                    },
                    {
                        "valueId": "36392",
                        "valueName": "15.2"
                    },
                    {
                        "valueId": "36393",
                        "valueName": "15.3"
                    },
                    {
                        "valueId": "36394",
                        "valueName": "15.4"
                    },
                    {
                        "valueId": "36395",
                        "valueName": "15.5"
                    },
                    {
                        "valueId": "36396",
                        "valueName": "15.6"
                    },
                    {
                        "valueId": "36397",
                        "valueName": "15.7"
                    },
                    {
                        "valueId": "36398",
                        "valueName": "15.8"
                    },
                    {
                        "valueId": "36400",
                        "valueName": "15.11"
                    },
                    {
                        "valueId": "36401",
                        "valueName": "16.2"
                    },
                    {
                        "valueId": "36587",
                        "valueName": "15.9"
                    },
                    {
                        "valueId": "36588",
                        "valueName": "15.4.5"
                    },
                    {
                        "valueId": "36602",
                        "valueName": "15.11_Voice"
                    },
                    {
                        "valueId": "36627",
                        "valueName": "16.2_Voice"
                    },
                    {
                        "valueId": "36648",
                        "valueName": "16.4"
                    },
                    {
                        "valueId": "36649",
                        "valueName": "16.5"
                    },
                    {
                        "valueId": "36674",
                        "valueName": "16.6"
                    },
                    {
                        "valueId": "36675",
                        "valueName": "16.7"
                    },
                    {
                        "valueId": "36676",
                        "valueName": "16.8"
                    },
                    {
                        "valueId": "36677",
                        "valueName": "16.9"
                    },
                    {
                        "valueId": "36678",
                        "valueName": "16.10"
                    },
                    {
                        "valueId": "36772",
                        "valueName": "16.10_Hdfc"
                    },
                    {
                        "valueId": "36825",
                        "valueName": "17.1"
                    },
                    {
                        "valueId": "36780",
                        "valueName": "17.4"
                    },
                    {
                        "valueId": "36837",
                        "valueName": "17.4_Hdfc"
                    },
                    {
                        "valueId": "36838",
                        "valueName": "17.7"
                    },
                    {
                        "valueId": "36839",
                        "valueName": "17.10"
                    },
                    {
                        "valueId": "36862",
                        "valueName": "18.2"
                    },
                    {
                        "valueId": "36936",
                        "valueName": "Roadmap"
                    },
                    {
                        "valueId": "37979",
                        "valueName": "18.5"
                    },
                    {
                        "valueId": "37980",
                        "valueName": "18.8"
                    },
                    {
                        "valueId": "37981",
                        "valueName": "18.11"
                    },
                    {
                        "valueId": "38042",
                        "valueName": "19.2"
                    },
                    {
                        "valueId": "38043",
                        "valueName": "19.5"
                    },
                    {
                        "valueId": "38044",
                        "valueName": "19.8"
                    },
                    {
                        "valueId": "38045",
                        "valueName": "19.11"
                    },
                    {
                        "valueId": "39127",
                        "valueName": "19.8.1"
                    },
                    {
                        "valueId": "39158",
                        "valueName": "19.11_mobile"
                    },
                    {
                        "valueId": "39162",
                        "valueName": "19.8.1_Bug_L3"
                    },
                    {
                        "valueId": "39163",
                        "valueName": "19.8.1_Regression"
                    },
                    {
                        "valueId": "39207",
                        "valueName": "19.11_Bug_L3"
                    },
                    {
                        "valueId": "39208",
                        "valueName": "19.11_Regression"
                    },
                    {
                        "valueId": "39276",
                        "valueName": "20.2"
                    },
                    {
                        "valueId": "39280",
                        "valueName": "19.11.1"
                    },
                    {
                        "valueId": "39281",
                        "valueName": "19.11.1_Bug_L3"
                    },
                    {
                        "valueId": "39282",
                        "valueName": "19.11.1_Regression"
                    },
                    {
                        "valueId": "39286",
                        "valueName": "20.2_Bug_L3"
                    },
                    {
                        "valueId": "39287",
                        "valueName": "20.2_Regression"
                    },
                    {
                        "valueId": "39417",
                        "valueName": "Release_Backlog"
                    },
                    {
                        "valueId": "39441",
                        "valueName": "20.4"
                    },
                    {
                        "valueId": "39442",
                        "valueName": "20.4_Bug_L3"
                    },
                    {
                        "valueId": "39443",
                        "valueName": "20.4_Regression"
                    },
                    {
                        "valueId": "39552",
                        "valueName": "20.7"
                    },
                    {
                        "valueId": "39553",
                        "valueName": "20.10"
                    },
                    {
                        "valueId": "39595",
                        "valueName": "26.1"
                    },
                    {
                        "valueId": "39616",
                        "valueName": "20.1.02"
                    },
                    {
                        "valueId": "39683",
                        "valueName": "20.2.1"
                    },
                    {
                        "valueId": "39684",
                        "valueName": "20.2.1_Bug_L3"
                    },
                    {
                        "valueId": "39717",
                        "valueName": "20.1.03"
                    },
                    {
                        "valueId": "39788",
                        "valueName": "20.1.04"
                    },
                    {
                        "valueId": "39891",
                        "valueName": "20.4_Top_Value_Drivers"
                    },
                    {
                        "valueId": "40080",
                        "valueName": "20.2.1_Regression"
                    },
                    {
                        "valueId": "40101",
                        "valueName": "20.2_Customer_Issue"
                    },
                    {
                        "valueId": "40115",
                        "valueName": "Incorrect_Fix_Version"
                    },
                    {
                        "valueId": "42148",
                        "valueName": "20.4.1"
                    },
                    {
                        "valueId": "42248",
                        "valueName": "20.7_Bug_L3"
                    },
                    {
                        "valueId": "42281",
                        "valueName": "20.4.1_Bug_L3"
                    },
                    {
                        "valueId": "43282",
                        "valueName": "20.4.1_Regression"
                    },
                    {
                        "valueId": "43315",
                        "valueName": "26.4"
                    },
                    {
                        "valueId": "43316",
                        "valueName": "26.7"
                    },
                    {
                        "valueId": "43317",
                        "valueName": "26.10"
                    },
                    {
                        "valueId": "43639",
                        "valueName": "20.7.1"
                    },
                    {
                        "valueId": "43773",
                        "valueName": "20.7_Regression"
                    },
                    {
                        "valueId": "43809",
                        "valueName": "20.10_Bug_L3"
                    },
                    {
                        "valueId": "44622",
                        "valueName": "20.10_Regression"
                    },
                    {
                        "valueId": "44689",
                        "valueName": "20.7.1_Regression"
                    },
                    {
                        "valueId": "45278",
                        "valueName": "26.1_Bug_L3"
                    },
                    {
                        "valueId": "45824",
                        "valueName": "26.1_Regression"
                    },
                    {
                        "valueId": "46227",
                        "valueName": "Test12.3"
                    },
                    {
                        "valueId": "46342",
                        "valueName": "test_FixVersion_20.00"
                    },
                    {
                        "valueId": "46855",
                        "valueName": "26.4_Bug_L3"
                    },
                    {
                        "valueId": "47099",
                        "valueName": "WK42_43_Patch"
                    },
                    {
                        "valueId": "47163",
                        "valueName": "26.1.1"
                    },
                    {
                        "valueId": "47419",
                        "valueName": "26.4.1"
                    },
                    {
                        "valueId": "48468",
                        "valueName": "26.4_Regression"
                    },
                    {
                        "valueId": "48552",
                        "valueName": "26.1.1_Bug_L3"
                    },
                    {
                        "valueId": "48584",
                        "valueName": "26.1.1_Regression"
                    }
                ],
                "value": [
                    "26.1_Bug_L3"
                ]
            },
            {
                "id": "customfield_22928",
                "value": [
                    "No"
                ],
                "required": true,
                "fieldName": "Is KB Documentation  Required?",
                "fieldType": "option",
                "definedValues": [
                    {
                        "valueId": "60843",
                        "valueName": "Yes, Release Notes"
                    },
                    {
                        "valueId": "60844",
                        "valueName": "Yes, Article"
                    },
                    {
                        "valueId": "60845",
                        "valueName": "Yes,Release Notes + Article"
                    },
                    {
                        "valueId": "60066",
                        "valueName": "No"
                    }
                ]
            },
            {
                "id": "customfield_22801",
                "value": [
                    "Accessibility"
                ],
                "required": true,
                "fieldName": "Modules / Sub-Module",
                "fieldType": "option-with-child",
                "definedValues": [
                    {
                        "valueId": "70956",
                        "valueName": "Accessibility"
                    },
                    {
                        "valueId": "59411",
                        "valueName": "Adhoc"
                    },
                    {
                        "valueId": "59397",
                        "valueName": "Adoption Metrics"
                    },
                    {
                        "valueId": "59337",
                        "valueName": "Ads Publishing"
                    },
                    {
                        "valueId": "59360",
                        "valueName": "Ads Reporting"
                    },
                    {
                        "valueId": "59365",
                        "valueName": "Ads-Integrations"
                    },
                    {
                        "valueId": "64558",
                        "valueName": "Advertising Core"
                    },
                    {
                        "valueId": "59385",
                        "valueName": "Advocacy"
                    },
                    {
                        "valueId": "57502",
                        "valueName": "Agent Assist"
                    },
                    {
                        "valueId": "57513",
                        "valueName": "Agent Desktop"
                    },
                    {
                        "valueId": "57510",
                        "valueName": "AI+ Studio"
                    },
                    {
                        "valueId": "59407",
                        "valueName": "API Suite & Webhooks"
                    },
                    {
                        "valueId": "64371",
                        "valueName": "Benchmarking"
                    },
                    {
                        "valueId": "57789",
                        "valueName": "Care Integrations"
                    },
                    {
                        "valueId": "59393",
                        "valueName": "CFM"
                    },
                    {
                        "valueId": "59333",
                        "valueName": "Channels"
                    },
                    {
                        "valueId": "57500",
                        "valueName": "Community"
                    },
                    {
                        "valueId": "59395",
                        "valueName": "Connector Upgrades"
                    },
                    {
                        "valueId": "59336",
                        "valueName": "Content Marketing"
                    },
                    {
                        "valueId": "57508",
                        "valueName": "Conversational Agents"
                    },
                    {
                        "valueId": "59349",
                        "valueName": "Creatives"
                    },
                    {
                        "valueId": "59399",
                        "valueName": "CRM Connectors"
                    },
                    {
                        "valueId": "59403",
                        "valueName": "CRM Iframe"
                    },
                    {
                        "valueId": "68372",
                        "valueName": "Cross-Module"
                    },
                    {
                        "valueId": "68975",
                        "valueName": "Cross-Module-Insights"
                    },
                    {
                        "valueId": "67308",
                        "valueName": "CXM"
                    },
                    {
                        "valueId": "66848",
                        "valueName": "CXM Mobile App"
                    },
                    {
                        "valueId": "59328",
                        "valueName": "DAM"
                    },
                    {
                        "valueId": "68034",
                        "valueName": "Data Security & Compliance"
                    },
                    {
                        "valueId": "59384",
                        "valueName": "Distributed"
                    },
                    {
                        "valueId": "59330",
                        "valueName": "Engagement"
                    },
                    {
                        "valueId": "59396",
                        "valueName": "Engineering track"
                    },
                    {
                        "valueId": "72111",
                        "valueName": "Entity Studio"
                    },
                    {
                        "valueId": "59398",
                        "valueName": "Extensions"
                    },
                    {
                        "valueId": "59331",
                        "valueName": "Governance"
                    },
                    {
                        "valueId": "57506",
                        "valueName": "Inbound Voice"
                    },
                    {
                        "valueId": "58738",
                        "valueName": "Infra"
                    },
                    {
                        "valueId": "66631",
                        "valueName": "Insight as Entity"
                    },
                    {
                        "valueId": "59386",
                        "valueName": "Insights"
                    },
                    {
                        "valueId": "64920",
                        "valueName": "Integrations"
                    },
                    {
                        "valueId": "57501",
                        "valueName": "Knowledge Base"
                    },
                    {
                        "valueId": "64370",
                        "valueName": "Listening"
                    },
                    {
                        "valueId": "57509",
                        "valueName": "Live Chat"
                    },
                    {
                        "valueId": "59383",
                        "valueName": "Live Chat SDK"
                    },
                    {
                        "valueId": "59334",
                        "valueName": "Marketing"
                    },
                    {
                        "valueId": "59394",
                        "valueName": "Marketplace"
                    },
                    {
                        "valueId": "64373",
                        "valueName": "Media Insights"
                    },
                    {
                        "valueId": "57497",
                        "valueName": "Outbound Voice"
                    },
                    {
                        "valueId": "60369",
                        "valueName": "Platform"
                    },
                    {
                        "valueId": "68804",
                        "valueName": "Pricing & Packaging"
                    },
                    {
                        "valueId": "64372",
                        "valueName": "Product & Location Insights"
                    },
                    {
                        "valueId": "59335",
                        "valueName": "Project Management"
                    },
                    {
                        "valueId": "59327",
                        "valueName": "Publishing"
                    },
                    {
                        "valueId": "57512",
                        "valueName": "Quality Management & Conversational Analytics"
                    },
                    {
                        "valueId": "66136",
                        "valueName": "Reply Box"
                    },
                    {
                        "valueId": "57511",
                        "valueName": "Reporting"
                    },
                    {
                        "valueId": "64557",
                        "valueName": "Resource Management"
                    },
                    {
                        "valueId": "60372",
                        "valueName": "Sandbox"
                    },
                    {
                        "valueId": "59332",
                        "valueName": "Security"
                    },
                    {
                        "valueId": "57503",
                        "valueName": "Social, Messaging & Email"
                    },
                    {
                        "valueId": "59382",
                        "valueName": "Space Mobile App"
                    },
                    {
                        "valueId": "57499",
                        "valueName": "Supervisor Console"
                    },
                    {
                        "valueId": "59166",
                        "valueName": "Survey"
                    },
                    {
                        "valueId": "59329",
                        "valueName": "UGC"
                    },
                    {
                        "valueId": "57507",
                        "valueName": "Unified Routing"
                    },
                    {
                        "valueId": "68805",
                        "valueName": "Usability"
                    },
                    {
                        "valueId": "59373",
                        "valueName": "Value Adds & Settings"
                    },
                    {
                        "valueId": "64374",
                        "valueName": "Visual Insights"
                    },
                    {
                        "valueId": "57505",
                        "valueName": "Voice Connect"
                    },
                    {
                        "valueId": "57546",
                        "valueName": "Workflow++"
                    },
                    {
                        "valueId": "57504",
                        "valueName": "Workforce Management"
                    }
                ]
            },
            {
                "id": "customfield_18501",
                "required": true,
                "fieldName": "Functional Solution",
                "fieldType": "array",
                "definedValues": [
                    {
                        "valueId": "26208",
                        "valueName": "Advertising"
                    },
                    {
                        "valueId": "31072",
                        "valueName": "Advocacy"
                    },
                    {
                        "valueId": "64111",
                        "valueName": "AI"
                    },
                    {
                        "valueId": "31273",
                        "valueName": "Benchmarking"
                    },
                    {
                        "valueId": "26210",
                        "valueName": "Care"
                    },
                    {
                        "valueId": "68728",
                        "valueName": "Certificates"
                    },
                    {
                        "valueId": "60267",
                        "valueName": "CFM"
                    },
                    {
                        "valueId": "75295",
                        "valueName": "CXM"
                    },
                    {
                        "valueId": "34162",
                        "valueName": "CXMW - (HDFC CRM)"
                    },
                    {
                        "valueId": "31093",
                        "valueName": "Display"
                    },
                    {
                        "valueId": "34010",
                        "valueName": "Distributed"
                    },
                    {
                        "valueId": "68730",
                        "valueName": "Elastic-Search"
                    },
                    {
                        "valueId": "26212",
                        "valueName": "Engagement"
                    },
                    {
                        "valueId": "32513",
                        "valueName": "Hyperspace Design System"
                    },
                    {
                        "valueId": "72229",
                        "valueName": "Implementation"
                    },
                    {
                        "valueId": "30629",
                        "valueName": "Incubation/Platform"
                    },
                    {
                        "valueId": "31073",
                        "valueName": "Integrations"
                    },
                    {
                        "valueId": "30628",
                        "valueName": "Intuition"
                    },
                    {
                        "valueId": "33626",
                        "valueName": "IT Team"
                    },
                    {
                        "valueId": "32062",
                        "valueName": "ITOPS"
                    },
                    {
                        "valueId": "26207",
                        "valueName": "Marketing"
                    },
                    {
                        "valueId": "31084",
                        "valueName": "Mobile"
                    },
                    {
                        "valueId": "68729",
                        "valueName": "Mongo"
                    },
                    {
                        "valueId": "32435",
                        "valueName": "RED"
                    },
                    {
                        "valueId": "26209",
                        "valueName": "Research"
                    },
                    {
                        "valueId": "61026",
                        "valueName": "Security"
                    },
                    {
                        "valueId": "32039",
                        "valueName": "Self Serve"
                    },
                    {
                        "valueId": "34121",
                        "valueName": "Voice Telephony"
                    }
                ],
                "value": [
                    "Care"
                ]
            },
            {
                "id": "issuelinks",
                "required": true,
                "fieldName": "Linked Issues",
                "fieldType": "array",
                "definedValues": [],
                "value": [
                    "CARE-90685"
                ]
            },
            {
                "id": "description",
                "required": true,
                "fieldName": "Description",
                "fieldType": "string",
                "definedValues": [],
                "value": [
                    "Report Portal Dummy Bug"
                ]
            },
            {
                "id": "summary",
                "required": true,
                "fieldName": "Summary",
                "fieldType": "string",
                "definedValues": [],
                "value": [
                    "Report Portal Dummy Bug"
                ]
            },
            {
                "id": "customfield_18800",
                "value": [
                    "Yes"
                ],
                "required": true,
                "fieldName": "Caught by Automation",
                "fieldType": "option",
                "definedValues": [
                    {
                        "valueId": "26700",
                        "valueName": "Yes"
                    },
                    {
                        "valueId": "26701",
                        "valueName": "No"
                    }
                ]
            },
            {
                "id": "customfield_22858",
                "value": [
                    "Low"
                ],
                "required": true,
                "fieldName": "Severity",
                "fieldType": "option",
                "definedValues": [
                    {
                        "valueId": "58346",
                        "valueName": "Low"
                    },
                    {
                        "valueId": "58347",
                        "valueName": "Medium"
                    },
                    {
                        "valueId": "58348",
                        "valueName": "High"
                    },
                    {
                        "valueId": "58349",
                        "valueName": "Critical"
                    }
                ]
            }
        ],
        "backLinks": {
            "1292027": "https://reportportal.sprinklr.com/ui/#default_personal/launches/all/5416/1291809/1291810/1292027/log?item1Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED"
        }
    }
}"`

**Comment by iamansaxena** [comment]
Hey @Pink-Bumblebee did you get a chance to check this?
