### ISSUE TITLE
Launch Not finishing even after its completion, its still showing In Progress

### ISSUE THREAD

**Issue by narayan907** [reportportal/reportportal#543]
**Describe the bug**
...

**Expected behavior**
...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by DzmitryHumianiuk** [comment]
this situation appears when your test runner try to finish execution, but some of test cases are still in progress at this moment. 

take a look at the test cases, which has IN_PROGRESS state. They causes this situation.
Find out why they still in progress at the moment, when runner finalize all execution.
This will help you to make code clean.

**Resolution:**
We will remove this constraint in 5.0 on API side.
ETA for 5.0 is Jan-Feb2019

**Comment by narayan907** [comment]
No ,the test case failed, still its not finishing launch on suite level,check screen shot
![screen_082](https://user-images.githubusercontent.com/39002876/50286715-4cac4d80-0486-11e9-944d-6464dd7d6c2d.png)
![screen_083](https://user-images.githubusercontent.com/39002876/50286723-53d35b80-0486-11e9-8c51-9f098dd13efe.png)

**Comment by DzmitryHumianiuk** [comment]
@narayan907 than it can be 2 reasons:
1) `FinishLaunchRQ` sent before  `FinishTestItemRQ`. Or with the equal timestamp.
2) Due to any reasons, runner do not sent `FinishLaunchRQ`

Check the logs of you test automation. There should be the message, returned by ReportPortal.
This will give us a clue.

**Comment by evjlobanova** [comment]
Fixed in 5.0

**Comment by sunshine69** [comment]
Hi, I am using version 5.3.5 at the moment and still see this behavior.
Can you pls advise what to fix or debug it?
